### ISSUE TITLE
GPL for use as a library?

### ISSUE THREAD

**Issue by pombredanne** [wbsoft/parce#2]
Have you considered a GPL exception for usage as a library in a larger application?

**Comment by wbsoft** [comment]
I didn't yet consider, but I think I currently won't, because parce is in its early stages and I develop it for free (and for fun) in my free time, and like to contribute to a large(r) free software ecosystem.

**Comment by pombredanne** [comment]
Thank you for the reply. This is fair and this means I will not be able to consider this for use in my Apache-licensed libraries.
